#cloud-config
users:
  - name: root
    lock_passwd: false
    shell: /bin/bash
runcmd:
  - echo 'root:root' | chpasswd
  - sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
  - sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
  - sed -i 's/^PasswordAuthentication no/#PasswordAuthentication no/' /etc/ssh/sshd_config.d/60-cloudimg-settings.conf || true
  - systemctl restart ssh
